# Site settings
title: My portfolio
description: Francesco Loi portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Francesco Loi
user_description: I am a software developer with 5 years experience working in technology
user_title: Software Developer
email: francesco.loi@outlook.it
github_username:  QuiGonRazor

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
